version: "2.4"

services:
  app:
    build: .
    command: uvicorn code.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      SECRET_KEY: cd556488a2e354d6751a6ddd5cd299bcfb7e3ec6b106515f64a863d23119a230
    ports:
      - "8000:8000"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
